language: node_js
node_js:
  - '4.1'
before_install: npm install -g grunt-cli
install: npm install
script: grunt
addons:
  apt:
    packages:
      - sshpass
after_success:
  - ping -c3 $DEPLOY_HOST
  - echo $DEPLOY_PATH
  - echo $DEPLOY_USER
  - sshpass -e scp -r build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
