language: node_js
node_js:
  - '4.1'
before_install: npm install -g grunt-cli
install: npm install
script: grunt
addons:
  apt:
    packages:
      - sshpass
after_success:
  - sshpass -e scp -o StrictHostKeyChecking=no -r build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
